JSON_FILENAME = "tasks.json"
KEY_NEXT_ID = "nextID"
KEY_DELETED_IDS = "deletedIDs"
KEY_TASKS = "tasks"
KEY_ID = "task_id"
KEY_DESCRIPTION = "description"
KEY_STATUS = "status"
KEY_CREATED_AT = "createdAt"
KEY_UPDATED_AT = "updatedAt"
ERROR_NO_TASKS = "No tasks at the moment!"
ERROR_ID_NOT_FOUND = "No task with such id found!"
ERROR_ID_NOT_INT = "Error: ID must be a number"
ARGS_NUM_FOR_LIST_ALL_COMMAND = 2
ARGS_NUM_FOR_LIST_STATUS_COMMAND = 3
ARGS_NUM_FOR_SET_STATUS_COMMAND = 3
ARGS_NUM_MINIMAL = 2