CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    description TEXT NOT NULL
        CHECK (length(trim(description)) >= 3),

    status TEXT NOT NULL DEFAULT 'todo'
        CHECK (status IN ('todo', 'in-progress', 'done')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);